# Meta Data for SEO

## Homepage
title = "Akash Network"
titleSeparator = "-"
titleAddition = "Decentralized Computing Marketplace"
description = "Peer-to-Peer Marketplace for Computing Resources"

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["preview.png"]
ogLocale = "en_US"
domainTLD = "akash.network"
titleHome = "Akash Network"

## Twitter Cards
twitterSite = "@akashnet_"
twitterCreator = "@akashnet_"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Akash Network"
schemaAuthor = "Decentralized Cloud Foundation"
schemaAuthorTwitter = "https://twitter.com/akashnet_"
schemaAuthorLinkedIn = ""
schemaAuthorGitHub = "https://github.com/akash-network"
schemaLocale = "en-US"
schemaLogo = "logos/akash-logo-primary.png"
schemaLogoWidth = 1129
schemaLogoHeight = 224
schemaImage = "preview.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/akashnet_"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/akash-network"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 75
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1280x640 Center" # normalize image size

# Footer
footer = "© 2023 The Akash Network Authors | Documentation Distributed under CC BY 4.0"

# Feed
copyRight = "Copyright © 2023 The Decentralized Cloud Foundation"

# Alert
alert = true
# alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertDismissable = true
alertText = "<span class='fw-bold' style='font-size: 15px;'>The Incentivized Akash GPU Testnet is live:</span>  <a target='_blank' class='alert-link stretched-link' href='/gpu-testnet' rel='noopener noreferrer'><span style='font-size: 15px; text-decoration:none;'> Sign up to participate and earn rewards</span></a>."


# Meta Data for SEO

## Homepage


# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
docsRepo = "https://github.com/akash-network/website"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = true
lastMod = true

[sections]
  sectionNav = ["docs", "guides", "community", "token", "blog", "discussions"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
